### PR TITLE
fix: add dive validation to Subgraphs field of HeaderRules config struct

### PR DESCRIPTION
**Pull request by cs-clarence**
## Motivation and Context

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

### CODE REVIEW

**Comment by jensneuse** [comment]
@cs-clarence thanks for all the PRs, I'd love to chat with you! Are you available for a call? You can book here: https://wundergraph.com/meet/jens

**Comment by cs-clarence** [comment]
@jensneuse sure, I booked a call

**Comment by StarpTech** [comment]
@cs-clarence thank you

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
