### PR TITLE
fix: cannot implement multiple interfaces for interfaceObject

### PR DESCRIPTION
**Pull request by AndriiTsok**
I created two tests to indicate the use case I tried to do. I wanted to implement Updatable, Deletable, Shareable interfaces and make its implementation via interfaceObject. Cosmo works fine if Entity implements only 1 of these 3 interfaces... but fails when we do more than 1.

## Motivation and Context

Provided two tests that should help identifying the issue.

## TODO

- [x] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

### CODE REVIEW

**Comment by AndriiTsok** [comment]
For some reason `pull` force pushed and override the changes. Here is the reference to commit: https://github.com/wundergraph/cosmo/commit/f3c36733452c1416f98bbb84f4d4f16a91fabf1f

**Comment by StarpTech** [comment]
HI @AndriiTsok nothing on our end. According to the bot message, your bot has force pushed it. We don't use this bot internally.

**Comment by AndriiTsok** [comment]
@StarpTech so sorry for that! I will look what is the Pull app and why that happened. 

In the meantime, I will reopen the pull request with the beaking test. 
I will try to debug the issue myself, but I have a little experience debugging Go language apps/libs.

**Comment by Aenimus** [comment]
@AndriiTsok Thanks Andrii.

If you're referring to the problem you presented with this PR, the issue is completely self-contained within the composition (TypeScript) library. Go is not involved there.

I have not investigated yet, but there will be some incorrect validation logic explicitly concerning interfaceObjects.

**Comment by AndriiTsok** [comment]
I just open #1066 I will try to investigate and debug it myself as well. Thank you @Aenimus

**Pull request merged**
