### PR TITLE
feat: restructure navigation

### PR DESCRIPTION
**Pull request by Pagebakers**
Implemented various improvements and changes to improve navigation and deliver a more consistent experience.

- Added loading spinner on initial page load (the layout would only be loaded partially for a short while)
- Restructured navigation to make the app easier to navigate.
- Added breadcrumbs to graph screens
- Improved schema explorer, added type navigation on wider screens.
- Improved checks overview and detail pages
- Various minor style improvements

localhost_3000_wundergraph_graph_production_clients (3)
localhost_3000_wundergraph_graph_production_clients (2)
localhost_3000_wundergraph_graph_production_clients (1)
localhost_3000_wundergraph_graph_production_clients
localhost_3000_account_invitations (4)
localhost_3000_account_invitations (3)
localhost_3000_account_invitations (2)
Screenshot 2023-11-30 at 16 45 01
Screenshot 2023-11-30 at 17 19 26

### CODE REVIEW

**Review by jensneuse — APPROVED** [review]

**Review by thisisnithin — CHANGES_REQUESTED** [review]
Looks great. Small thing, invitations need to be seen separately. It serves as the only type of notification in the studio right now. I wouldnt couple it to user menu

In the checks table. I want to see the exact time when the check was run. Relative timing is not useful. In the check id page it is okay given there is a tooltip with the exact time.

Please align this 🙈 
image

**Comment by Pagebakers** [comment]
Alignment, i noticed, but forgot to update.

Invite notification, I moved it because it became a bit too cluttered and it's not a feature that's used on a daily basis. I did improve the accessibility of invitations see:

Screenshot 2023-11-30 at 17 27 18

**Comment by Pagebakers** [comment]
Updated Checks Passed to Checks Failed

**Comment by Pagebakers** [comment]
> What would the be url for the invitations ?

This is still the same

**Review by thisisnithin — APPROVED** [review]
LGTM 🚀

**Pull request merged**
