### PR TITLE
chore(router): use automic's CAS to allow to shutdown the router concurrently

### PR DESCRIPTION
**Pull request by git-hulk**
## Motivation and Context

It now uses load and store when checking if the server is shutdown, so it might introduce data race if calls the shutdown function at the same time. We can work around this by using CAS operation in atomic.

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [x] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [x] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @git-hulk, please follow the PR description template. For now, it would be enough if xz could briefly explain the issue and how your reproduce it.

**Comment by StarpTech** [comment]
Now, I understand the why. We have a race in main.go. Please add a proper PR description next time.

**Review by StarpTech — APPROVED** [review]
LGTM

**Comment by git-hulk** [comment]
@StarpTech Sure, thanks for your review. I have updated the summary and will follow the guidelines before submitting the PR.

**Pull request merged**
