### PR TITLE
fix(router): don't flush all redis keys while shutdown

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, shutdown router will flush all keys in Redis instance. This might cause unexpected behavior if users are using Redis instance for other purposes besides the rate limit. And from my understanding, it also makes no sense to delete all rate limiter keys once one of router instances was shutdowned.

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [x] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [x] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by git-hulk** [comment]
@StarpTech We're studying cosmo since we would like to introduce a gateway for GraphQL, and found this while going through the codebase. Would you mind having a look at this? I think it's a serious issue from my side.

**Comment by StarpTech** [comment]
Hi @git-hulk, this was an oversight from us, great catch! The goal here was to drain the connection. But this is not necessary.

**Comment by StarpTech** [comment]
The term flush has different meaning across the board and providers. 😌

**Comment by git-hulk** [comment]
@StarpTech Thanks for your reply and confirmation.

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
